version: "3.7"
services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PASS_SALT: ${SECRET_KEY}
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ERPY_PG_USER: erpy
      ERPY_PG_PASS: ${POSTGRES_PASSWORD}
      ERPY_PG_HOST: db
      ERPY_PG_PORT: 5432
      ERPY_PG_DB: ${POSTGRES_DB}
    ports:
      - 5000:5000

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 5200:5200
    # command: [nginx-debug, '-g', 'daemon off;']